config/routes.rb
Rails.application.routes.draw do
  resources :phonebooks
  get 'billing/index'

  get 'billing/view'

  get 'billing/index'

  resources :logs
  resources :calls
  mount RailsAdmin::Engine => '/atema', as: 'rails_admin'
  resources :companies
  root to: 'visitors#index'
  devise_for :users, :skip => [:registrations]
  as :user do
  get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
  put 'users' => 'devise/registrations#update', :as => 'user_registration'

  # Call Handling Routes
  get 'call_handler/inbound_call' => 'call_handler#inbound_call'
  get 'call_handler/call_recording' => 'call_handler#call_recording'
  get 'call_handler/resend_email' => 'call_handler#resend_email', as: :resend_email
  get 'call_handler/delete_single_recording' => 'call_handler#delete_single_recording', as: :delete_single_recording

end
  resources :users
end

app/models/call.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: calls
#
#  id               :integer          not null, primary key
#  callsid          :string(255)
#  recordingsid     :string(255)
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  company_id       :integer
#  from             :string(255)
#  duration         :string(255)
#  status           :string(255)
#  recordingDeleted :datetime
#

class Call < ActiveRecord::Base
  belongs_to :company
  has_many :logs, dependent: :destroy

  def isbillable; end
end

app/controllers/calls_controller.rb
# frozen_string_literal: true

class CallsController < ApplicationController
  load_and_authorize_resource
  before_action :set_call, only: %i[show edit update destroy]

  # GET /calls
  # GET /calls.json
  def index
    @calls = current_user.company.calls
  end

  # GET /calls/1
  # GET /calls/1.json
  def show
    @logs = @call.logs
  end

  # GET /calls/new
  def new
    @call = Call.new
  end

  # GET /calls/1/edit
  def edit; end

  # POST /calls
  # POST /calls.json
  def create
    @call = Call.new(call_params)

    respond_to do |format|
      if @call.save
        format.html { redirect_to @call, notice: 'Call was successfully created.' }
        format.json { render :show, status: :created, location: @call }
      else
        format.html { render :new }
        format.json { render json: @call.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /calls/1
  # PATCH/PUT /calls/1.json
  def update
    respond_to do |format|
      if @call.update(call_params)
        format.html { redirect_to @call, notice: 'Call was successfully updated.' }
        format.json { render :show, status: :ok, location: @call }
      else
        format.html { render :edit }
        format.json { render json: @call.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calls/1
  # DELETE /calls/1.json
  def destroy
    @call.destroy
    respond_to do |format|
      format.html { redirect_to calls_url, notice: 'Call was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_call
    @call = Call.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def call_params
    params.require(:call).permit(:callsid, :recordingsid)
  end
end

app/helpers/calls_helper.rb
module CallsHelper
end

app/views/calls/_form.html.erb
<%= form_for(@call) do |f| %>
  <% if @call.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@call.errors.count, "error") %> prohibited this call from being saved:</h2>

      <ul>
      <% @call.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :callsid %><br>
    <%= f.text_field :callsid %>
  </div>
  <div class="field">
    <%= f.label :recordingsid %><br>
    <%= f.text_field :recordingsid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/calls/edit.html.erb
<h1>Editing Call</h1>

<%= render 'form' %>

<%= link_to 'Show', @call %> |
<%= link_to 'Back', calls_path %>

app/views/calls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Calls</h1>

<table>
  <thead>
    <tr>
      <th>Callsid</th>
      <th>Recordingsid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @calls.each do |call| %>
      <tr>
        <td><%= call.callsid %></td>
        <td><%= call.recordingsid %></td>
        <td><%= link_to 'Show', call %></td>
        <td><%= link_to 'Edit', edit_call_path(call) %></td>
        <td><%= link_to 'Destroy', call, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Call', new_call_path %>

app/views/calls/new.html.erb
<h1>New Call</h1>

<%= render 'form' %>

<%= link_to 'Back', calls_path %>

app/views/calls/show.html.erb
<h1>Call Information</h1>
<p>
  <strong>Created:</strong>
  <%= @call.created_at %>
</p>
<p>
  <strong>Status:</strong>
  <%= @call.status%>
</p>
<p>
  <strong>Call SID:</strong>
  <%= @call.callsid %>
</p>

<p>
  <strong>Recording SID:</strong>
  <%= @call.recordingsid %>
</p>
<p>
  <strong>Caller:</strong>
  <%= @call.from%>
</p>
<p>
  <strong>Duration:</strong>
  <%= @call.duration%> seconds
</p>

<h1>Logs</h1>

<% @logs.each do |log| %>
<b><%= log.created_at.to_s + ": "%></b><%=log.message %></br>
<% end %>
</br>
<%= link_to 'Back', root_path %>