config/routes.rb
Rails.application.routes.draw do
  resources :phonebooks
  get 'billing/index'

  get 'billing/view'

  get 'billing/index'

  resources :logs
  resources :calls
  mount RailsAdmin::Engine => '/atema', as: 'rails_admin'
  resources :companies
  root to: 'visitors#index'
  devise_for :users, :skip => [:registrations]
  as :user do
  get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
  put 'users' => 'devise/registrations#update', :as => 'user_registration'

  # Call Handling Routes
  get 'call_handler/inbound_call' => 'call_handler#inbound_call'
  get 'call_handler/call_recording' => 'call_handler#call_recording'
  get 'call_handler/resend_email' => 'call_handler#resend_email', as: :resend_email
  get 'call_handler/delete_single_recording' => 'call_handler#delete_single_recording', as: :delete_single_recording

end
  resources :users
end

app/models/phonebook.rb
# frozen_string_literal: true

class Phonebook < ActiveRecord::Base
  belongs_to :company
end

app/controllers/phonebooks_controller.rb
# frozen_string_literal: true

class PhonebooksController < ApplicationController
  before_action :set_phonebook, only: %i[show edit update destroy]

  # GET /phonebooks
  # GET /phonebooks.json
  def index
    @phonebooks = current_user.company.phonebooks
  end

  # GET /phonebooks/1
  # GET /phonebooks/1.json
  def show; end

  # GET /phonebooks/new
  def new
    @phonebook = Phonebook.new
  end

  # GET /phonebooks/1/edit
  def edit; end

  # POST /phonebooks
  # POST /phonebooks.json
  def create
    @phonebook = Phonebook.new(phonebook_params)

    respond_to do |format|
      if @phonebook.save
        format.html { redirect_to @phonebook, notice: 'Phonebook entry was successfully created.' }
        format.json { render :show, status: :created, location: @phonebook }
      else
        format.html { render :new }
        format.json { render json: @phonebook.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /phonebooks/1
  # PATCH/PUT /phonebooks/1.json
  def update
    respond_to do |format|
      if @phonebook.update(phonebook_params)
        format.html { redirect_to @phonebook, notice: 'Phonebook was successfully updated.' }
        format.json { render :show, status: :ok, location: @phonebook }
      else
        format.html { render :edit }
        format.json { render json: @phonebook.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phonebooks/1
  # DELETE /phonebooks/1.json
  def destroy
    @phonebook.destroy
    respond_to do |format|
      format.html { redirect_to phonebooks_url, notice: 'Phonebook was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_phonebook
    @phonebook = Phonebook.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def phonebook_params
    params.require(:phonebook).permit(:company_id, :number, :name)
  end
end

app/helpers/phonebooks_helper.rb
module PhonebooksHelper
end

app/views/phonebooks/_form.html.erb
<%= form_for(@phonebook) do |f| %>
  <% if @phonebook.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@phonebook.errors.count, "error") %> prohibited this phonebook entry from being saved:</h2>

      <ul>
      <% @phonebook.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">

    <%= f.hidden_field :company_id, value: current_user.company_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :number %><br>
    <%= f.text_field :number %>
  </div>

  <div class="actions">
    <%= f.submit "Create Phonebook Entry" %>
  </div>
<% end %>

app/views/phonebooks/edit.html.erb
<h1>Editing Phonebook Entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @phonebook %> |
<%= link_to 'Back', phonebooks_path %>

app/views/phonebooks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Phonebook Entries</h1>

<table id="1" border="1" class=" table table-striped table-bordered table-sm">
  <thead>
    <tr>

      <th>Number</th>
      <th>Name</th>
      <th colspan="2">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @phonebooks.each do |phonebook| %>
      <tr>

        <td><%= phonebook.number %></td>
        <td><%= phonebook.name %></td>
        <td><%= link_to 'Edit', edit_phonebook_path(phonebook) %>
        <%= link_to 'Destroy', phonebook, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Phonebook Entry', new_phonebook_path %>

app/views/phonebooks/new.html.erb
<h1>New Phonebook Entry</h1>

<%= render 'form' %>

<%= link_to 'Back', phonebooks_path %>

app/views/phonebooks/show.html.erb
<p id="notice"><%= notice %></p>



<p>
  <strong>Number:</strong>
  <%= @phonebook.number %>
</p>

<p>
  <strong>Name:</strong>
  <%= @phonebook.name %>
</p>

<%= link_to 'Edit', edit_phonebook_path(@phonebook) %> |
<%= link_to 'Back', phonebooks_path %>