config/routes.rb
Rails.application.routes.draw do
  resources :phonebooks
  get 'billing/index'

  get 'billing/view'

  get 'billing/index'

  resources :logs
  resources :calls
  mount RailsAdmin::Engine => '/atema', as: 'rails_admin'
  resources :companies
  root to: 'visitors#index'
  devise_for :users, :skip => [:registrations]
  as :user do
  get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
  put 'users' => 'devise/registrations#update', :as => 'user_registration'

  # Call Handling Routes
  get 'call_handler/inbound_call' => 'call_handler#inbound_call'
  get 'call_handler/call_recording' => 'call_handler#call_recording'
  get 'call_handler/resend_email' => 'call_handler#resend_email', as: :resend_email
  get 'call_handler/delete_single_recording' => 'call_handler#delete_single_recording', as: :delete_single_recording

end
  resources :users
end

app/models/company.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: companies
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  email      :string(255)
#  message    :string(255)
#  number     :string(255)
#  accountSID :string(255)
#  auth_token :string(255)
#

class Company < ActiveRecord::Base
  has_many :users,  dependent: :destroy
  has_many :calls,  dependent: :destroy
  has_many :phonebooks, dependent: :destroy
end

app/controllers/companies_controller.rb
# frozen_string_literal: true

class CompaniesController < ApplicationController
  load_and_authorize_resource
  before_action :set_company, only: %i[show edit update destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show; end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit; end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_company
    @company = Company.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def company_params
    params.require(:company).permit(:name, :email, :message, :number)
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

   <div class="form-group">
    <%= f.label :message %><br>
    <%= f.text_field :message, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :number %><br>
    <%= f.text_field :number, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit 'Update', :class => 'button right' %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<div class="authform">
<h1>Editing Company</h1>

<%= render 'form' %>
</div>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Companies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>