config/routes.rb
Rails.application.routes.draw do
  resources :phonebooks
  get 'billing/index'

  get 'billing/view'

  get 'billing/index'

  resources :logs
  resources :calls
  mount RailsAdmin::Engine => '/atema', as: 'rails_admin'
  resources :companies
  root to: 'visitors#index'
  devise_for :users, :skip => [:registrations]
  as :user do
  get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
  put 'users' => 'devise/registrations#update', :as => 'user_registration'

  # Call Handling Routes
  get 'call_handler/inbound_call' => 'call_handler#inbound_call'
  get 'call_handler/call_recording' => 'call_handler#call_recording'
  get 'call_handler/resend_email' => 'call_handler#resend_email', as: :resend_email
  get 'call_handler/delete_single_recording' => 'call_handler#delete_single_recording', as: :delete_single_recording

end
  resources :users
end

app/models/log.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: logs
#
#  id         :integer          not null, primary key
#  call_id    :integer
#  message    :text(65535)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Log < ActiveRecord::Base
  belongs_to :call
end

app/controllers/logs_controller.rb
# frozen_string_literal: true

class LogsController < ApplicationController
  load_and_authorize_resource
  before_action :set_log, only: %i[show edit update destroy]

  # GET /logs
  # GET /logs.json
  def index
    @logs = Log.all
  end

  # GET /logs/1
  # GET /logs/1.json
  def show; end

  # GET /logs/new
  def new
    @log = Log.new
  end

  # GET /logs/1/edit
  def edit; end

  # POST /logs
  # POST /logs.json
  def create
    @log = Log.new(log_params)

    respond_to do |format|
      if @log.save
        format.html { redirect_to @log, notice: 'Log was successfully created.'}
        format.json { render :show, status: :created, location: @log }
      else
        format.html { render :new }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /logs/1
  # PATCH/PUT /logs/1.json
  def update
    respond_to do |format|
      if @log.update(log_params)
        format.html { redirect_to @log, notice: 'Log was successfully updated.'}
        format.json { render :show, status: :ok, location: @log }
      else
        format.html { render :edit }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logs/1
  # DELETE /logs/1.json
  def destroy
    @log.destroy
    respond_to do |format|
      format.html { redirect_to logs_url, notice: 'Log was successfully destroyed.'}
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_log
    @log = Log.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def log_params
    params.require(:log).permit(:call_id, :message)
  end
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/views/logs/_form.html.erb
<%= form_for(@log) do |f| %>
  <% if @log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@log.errors.count, "error") %> prohibited this log from being saved:</h2>

      <ul>
      <% @log.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :call_id %><br>
    <%= f.text_field :call_id %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_field :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/logs/edit.html.erb
<h1>Editing Log</h1>

<%= render 'form' %>

<%= link_to 'Show', @log %> |
<%= link_to 'Back', logs_path %>

app/views/logs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Logs</h1>

<table>
  <thead>
    <tr>
      <th>Call</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @logs.each do |log| %>
      <tr>
        <td><%= log.call %></td>
        <td><%= log.message %></td>
        <td><%= link_to 'Show', log %></td>
        <td><%= link_to 'Edit', edit_log_path(log) %></td>
        <td><%= link_to 'Destroy', log, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Log', new_log_path %>

app/views/logs/new.html.erb
<h1>New Log</h1>

<%= render 'form' %>

<%= link_to 'Back', logs_path %>

app/views/logs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Call:</strong>
  <%= @log.call %>
</p>

<p>
  <strong>Message:</strong>
  <%= @log.message %>
</p>

<%= link_to 'Edit', edit_log_path(@log) %> |
<%= link_to 'Back', logs_path %>